l_arm:
  kinematics_solver: bender_l_arm_kinematics/LeftArmIKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
r_arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin  #kdl_kinematics_plugin/KDLKinematicsPluginasd #bender_r_arm_kinematics/RightArmIKFastKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
