# Robot base link
base_link: 'bender/base_link'

# Left gripper
l_gripper:
  # End effector group name
  end_effector_name: 'l_gripper'

  # Actuated joints in end effector
  joints : ['l_int_finger_joint', 'l_ext_finger_joint']

  # Open position
  pregrasp_posture : [0.5, 0.5]
  pregrasp_time_from_start : 4.0

  # Close position
  grasp_posture : [0.0, 0.0]
  grasp_time_from_start : 4.0

  # Desired pose from end effector to grasp - [x,y,z,r,p,y]
  grasp_pose_to_eef : [-0.18, 0.02, 0.0, 0.0, -1.57, 0.0]

  end_effector_parent_link: 'bender/l_wrist_pitch_link'

  # Cylindrical grasp generator params
  cylindrical_grasp_generator:
    approach_angle: 0.2
    yaw_angle_count: 50
    pitch_angle_count: 3
    pitch_angle_min: 0.0
    pitch_angle_max: 0.2
    roll_angle_count: 3
    roll_angle_min: 0.0
    roll_angle_max: 0.1
    pregrasp_count: 3
    pregrasp_min: 0.01
    pregrasp_max: 0.02
